insert into musics (name, state) values ('Portland', 'OR');
insert into musics (name, state) values ('Charlotte', 'NC');
insert into musics (name, state) values ('Atlanta', 'GA');
insert into musics (name, state) values ('San Diego', 'CA');
insert into musics (name, state) values ('New York City', 'NY');
insert into musics (name, state) values ('Portsmouth', 'VA');
insert into musics (name, state) values ('Fayetteville', 'NC');
insert into musics (name, state) values ('Los Angeles', 'CA');
insert into musics (name, state) values ('Boise', 'ID');
insert into musics (name, state) values ('Montgomery', 'AL');
insert into musics (name, state) values ('Tuscaloosa', 'AL');
insert into musics (name, state) values ('Hagerstown', 'MD');
insert into musics (name, state) values ('Denver', 'CO');
insert into musics (name, state) values ('Van Nuys', 'CA');
insert into musics (name, state) values ('San Diego', 'CA');
insert into musics (name, state) values ('Fort Pierce', 'FL');
insert into musics (name, state) values ('Chicago', 'IL');
insert into musics (name, state) values ('Pensacola', 'FL');
insert into musics (name, state) values ('San Jose', 'CA');
insert into musics (name, state) values ('Philadelphia', 'PA');
insert into musics (name, state) values ('Sioux City', 'IA');
insert into musics (name, state) values ('Chicago', 'IL');
insert into musics (name, state) values ('El Paso', 'TX');
insert into musics (name, state) values ('Huntington', 'WV');
insert into musics (name, state) values ('New York City', 'NY');
insert into musics (name, state) values ('San Francisco', 'CA');
insert into musics (name, state) values ('Rochester', 'NY');
insert into musics (name, state) values ('Dallas', 'TX');
insert into musics (name, state) values ('Sacramento', 'CA');
insert into musics (name, state) values ('Boca Raton', 'FL');
insert into musics (name, state) values ('Fresno', 'CA');
insert into musics (name, state) values ('Young America', 'MN');
insert into musics (name, state) values ('Memphis', 'TN');
insert into musics (name, state) values ('Shreveport', 'LA');
insert into musics (name, state) values ('Edmond', 'OK');
insert into musics (name, state) values ('New York City', 'NY');
insert into musics (name, state) values ('Brooklyn', 'NY');
insert into musics (name, state) values ('San Diego', 'CA');
insert into musics (name, state) values ('Birmingham', 'AL');
insert into musics (name, state) values ('Atlanta', 'GA');
insert into musics (name, state) values ('Columbia', 'MO');
insert into musics (name, state) values ('White Plains', 'NY');
insert into musics (name, state) values ('White Plains', 'NY');
insert into musics (name, state) values ('Fayetteville', 'NC');
insert into musics (name, state) values ('Sterling', 'VA');
insert into musics (name, state) values ('Gulfport', 'MS');
insert into musics (name, state) values ('Washington', 'DC');
insert into musics (name, state) values ('Tacoma', 'WA');
insert into musics (name, state) values ('Amarillo', 'TX');
insert into musics (name, state) values ('Cincinnati', 'OH');
insert into musics (name, state) values ('Fresno', 'CA');
insert into musics (name, state) values ('Boston', 'MA');
insert into musics (name, state) values ('Oakland', 'CA');
insert into musics (name, state) values ('Saint Petersburg', 'FL');
insert into musics (name, state) values ('Portsmouth', 'VA');
insert into musics (name, state) values ('Homestead', 'FL');
insert into musics (name, state) values ('Decatur', 'GA');
insert into musics (name, state) values ('Riverside', 'CA');
insert into musics (name, state) values ('Portsmouth', 'NH');
insert into musics (name, state) values ('Roanoke', 'VA');
insert into musics (name, state) values ('Irvine', 'CA');
insert into musics (name, state) values ('Hollywood', 'FL');
insert into musics (name, state) values ('Orlando', 'FL');
insert into musics (name, state) values ('Amarillo', 'TX');
insert into musics (name, state) values ('San Francisco', 'CA');
insert into musics (name, state) values ('Louisville', 'KY');
insert into musics (name, state) values ('Albuquerque', 'NM');
insert into musics (name, state) values ('Flint', 'MI');
insert into musics (name, state) values ('Shreveport', 'LA');
insert into musics (name, state) values ('Washington', 'DC');
insert into musics (name, state) values ('Boise', 'ID');
insert into musics (name, state) values ('Pittsburgh', 'PA');
insert into musics (name, state) values ('Sacramento', 'CA');
insert into musics (name, state) values ('Fort Lauderdale', 'FL');
insert into musics (name, state) values ('Pensacola', 'FL');
insert into musics (name, state) values ('Dallas', 'TX');
insert into musics (name, state) values ('Macon', 'GA');
insert into musics (name, state) values ('Fort Lauderdale', 'FL');
insert into musics (name, state) values ('Columbus', 'GA');
insert into musics (name, state) values ('Wilkes Barre', 'PA');
insert into musics (name, state) values ('Yakima', 'WA');
insert into musics (name, state) values ('Syracuse', 'NY');
insert into musics (name, state) values ('Kansas City', 'MO');
insert into musics (name, state) values ('Mobile', 'AL');
insert into musics (name, state) values ('Santa Fe', 'NM');
insert into musics (name, state) values ('Boca Raton', 'FL');
insert into musics (name, state) values ('Dallas', 'TX');
insert into musics (name, state) values ('Albany', 'NY');
insert into musics (name, state) values ('Des Moines', 'IA');
insert into musics (name, state) values ('Elizabeth', 'NJ');
insert into musics (name, state) values ('Fayetteville', 'NC');
insert into musics (name, state) values ('Portsmouth', 'VA');
insert into musics (name, state) values ('Houston', 'TX');
insert into musics (name, state) values ('Seattle', 'WA');
insert into musics (name, state) values ('Bakersfield', 'CA');
insert into musics (name, state) values ('Cleveland', 'OH');
insert into musics (name, state) values ('Baltimore', 'MD');
insert into musics (name, state) values ('El Paso', 'TX');
insert into musics (name, state) values ('Dallas', 'TX');
insert into musics (name, state) values ('Port Washington', 'NY');